---
# NETSIBLE — Ansible Inventory
all:
  children:
    mikrotik_routers:
      hosts:
        router_gw:
          ansible_host: 192.168.88.1
          ansible_user: admin
          ansible_password: ""
          ansible_connection: network_cli
          ansible_network_os: community.routeros.routeros
