from flask import Blueprint, render_template, request, flash, redirect, url_for, send_file
import io

backup_bp = Blueprint('backup', __name__, url_prefix='/backup')

# In-memory mock data for demonstration
MOCK_BACKUPS = [
    {"id": 1, "device_name": "Router-GW", "filename": "Router-GW_20260504.rsc", "date": "2026-05-04 10:00:00", "size": "15 KB", "status": "Success"},
    {"id": 2, "device_name": "Router-Branch1", "filename": "Router-Branch1_20260503.rsc", "date": "2026-05-03 09:30:00", "size": "12 KB", "status": "Success"},
]

MOCK_DEVICES = ["Router-GW", "Router-Branch1", "Router-Branch2", "Router-Lab", "AP-Office"]

@backup_bp.route('/')
def index():
    return render_template('backup/index.html', backups=MOCK_BACKUPS, devices=MOCK_DEVICES)

@backup_bp.route('/run', methods=['POST'])
def run_backup():
    device = request.form.get('device')
    if device:
        # Simulate backup logic
        new_id = max([b['id'] for b in MOCK_BACKUPS], default=0) + 1
        new_backup = {
            "id": new_id,
            "device_name": device,
            "filename": f"{device}_new_backup.rsc",
            "date": "Just now",
            "size": "14 KB",
            "status": "Success"
        }
        MOCK_BACKUPS.insert(0, new_backup)
        flash(f'Proses backup untuk {device} berhasil dijalankan!', 'success')
    else:
        flash('Device tidak valid.', 'danger')
    return redirect(url_for('backup.index'))

@backup_bp.route('/schedule/<device_name>', methods=['POST'])
def schedule_backup(device_name):
    interval = request.form.get('interval')
    time = request.form.get('time')
    enabled = request.form.get('enable_schedule') == 'on'
    
    status = "diaktifkan" if enabled else "dinonaktifkan"
    flash(f'Jadwal backup rutin untuk {device_name} telah {status} (Interval: {interval}, Waktu: {time}).', 'success')
    return redirect(url_for('backup.index'))

@backup_bp.route('/download/<int:backup_id>')
def download_backup(backup_id):
    backup = next((b for b in MOCK_BACKUPS if b['id'] == backup_id), None)
    if backup:
        # Create a dummy file in memory
        file_content = f"# Backup for {backup['device_name']}\n# File: {backup['filename']}\n# Generated by NETSIBLE\n"
        mem = io.BytesIO()
        mem.write(file_content.encode('utf-8'))
        mem.seek(0)
        return send_file(
            mem,
            as_attachment=True,
            download_name=backup['filename'],
            mimetype='text/plain'
        )
    flash('File backup tidak ditemukan.', 'danger')
    return redirect(url_for('backup.index'))

@backup_bp.route('/restore/<int:backup_id>', methods=['POST'])
def restore_backup(backup_id):
    backup = next((b for b in MOCK_BACKUPS if b['id'] == backup_id), None)
    if backup:
        # Simulate restore logic
        flash(f"Konfigurasi dari file {backup['filename']} berhasil di-restore ke perangkat {backup['device_name']}.", 'success')
    else:
        flash('File backup tidak ditemukan.', 'danger')
    return redirect(url_for('backup.index'))

@backup_bp.route('/delete/<int:backup_id>', methods=['POST'])
def delete_backup(backup_id):
    global MOCK_BACKUPS
    backup = next((b for b in MOCK_BACKUPS if b['id'] == backup_id), None)
    if backup:
        MOCK_BACKUPS = [b for b in MOCK_BACKUPS if b['id'] != backup_id]
        flash(f"File backup {backup['filename']} berhasil dihapus.", 'success')
    else:
        flash('File backup tidak ditemukan.', 'danger')
    return redirect(url_for('backup.index'))
